// React-project/src/productcard.jsx
import React from 'react';

const ProductCard = ({ product }) => (
  <div className="card shadow p-3">
    <img
      src={product.image}
      className="card-img-top"
      alt={product.title}
      style={{ height: '200px', objectFit: 'contain' }}
    />
    <div className="card-body">
      <h5 className="card-title">{product.title}</h5>
      <p className="card-text">Price: ${product.price}</p>
      <button className="btn btn-success">Add to Cart</button>
    </div>
  </div>
);

export default ProductCard;

// Angular-project/src/app/menu/product-list/product-card/product-card.component.ts
import { Component, Input } from '@angular/core';
import { CartService } from '../../../services/cart.service';
import { LoginService } from '../../../services/login.service';
@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.css']
})
export class ProductCardComponent {
  @Input() flower: any;

  constructor(private cartService: CartService,private loginService: LoginService) {}

  addToCart(): void {
  
      this.cartService.addToCart(this.flower);
      alert(`Product added to cart: ${this.flower}`);


  }
}

<div class="product-card card shadow-sm">
    <img
        src="http://localhost:8090/{{ flower.image }}"
        class="card-img-top"
        alt="flower Image"
    />
    <div class="card-body text-center">
        <h3 class="card-title">{{ flower.name }}</h3>
        <p class="card-text">{{ flower.description }}</p>
        <p class="card-text"><strong>Price:</strong> ${{ flower.price }}</p>
        <p class="card-text"><strong>Rating:</strong> ⭐ {{ flower.rating }}</p>
        <button class="btn btn-success w-100 mt-2" (click)="addToCart()">
            🛒 Add to Cart
        </button>
    </div>
</div>
